-d C:\Users\Ortiz\OneDrive\Desktop\VHDL projects\Artificial_Horizon\impl\gwsynthesis\Artificial_Horizon.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Ortiz\OneDrive\Desktop\VHDL projects\Artificial_Horizon\src\Artificial_Horizon.cst
-cfg C:\Users\Ortiz\OneDrive\Desktop\VHDL projects\Artificial_Horizon\impl\pnr\device.cfg
-gao_crc 0010010001101000
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
-rtl_gao
